name: Run SOAPUI Project on Windows

on:
  workflow_dispatch:
  schedule:
    - cron: '20 16 * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install WSL and Ubuntu
      run: |
        wsl --install -d Ubuntu
        wsl --set-default-version 1
      shell: pwsh

    - name: Run SoapUI Tests
      run: |
        wsl wget https://dl.eviware.com/soapuios/5.7.2/SoapUI-5.7.2-linux-bin.tar.gz
        wsl tar -xzf SoapUI-5.7.2-linux-bin.tar.gz -C /opt/
        wsl rm SoapUI-5.7.2-linux-bin.tar.gz
        wsl /opt/SoapUI-5.7.2/bin/testrunner.sh -s "CountryInfoServiceSoapBinding TestSuite" -r -a -f results /path/to/CountryInfoService-soapui-project.xml
      shell: pwsh

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: SoapUI-results
        path: results/
